### ISSUE TITLE
Add a command to auto create a duplicate settings file.

### ISSUE THREAD

**Issue by Mixail132** [RuslanSlepuhin/server_bot#327]
#### Description:
The duplicate settings file is needed to run the Django app in a developing mode and use tge standart DRF web interface when developing. 
The dev settings file is a file that contains settings in developing mode.
That;s the ability to run the code using nested DRF interface.

 - [x]  Create a management command to create the dev settings file.
 - [x]  Change the existing task for launching the project on a localhost.
 - [x]  Add a docker entrypoint.
 - [x]  Ignore the dev settings file once it has been created.

**Comment by smbd1368** [comment]
my_project/
│
├── my_project/
│   ├── __init__.py
│   ├── settings.py        # Optional: keep this as the base settings
│   ├── settings_dev.py    # Development settings
│   ├── settings_prod.py   # Production settings


export DJANGO_SETTINGS_MODULE=my_project.settings_dev
python manage.py runserver

**Comment by Mixail132** [comment]
> my_project/ │ ├── my_project/ │ ├── **init**.py │ ├── settings.py # Optional: keep this as the base settings │ ├── settings_dev.py # Development settings │ ├── settings_prod.py # Production settings
> 
> export DJANGO_SETTINGS_MODULE=my_project.settings_dev python manage.py runserver

Thank you! But I've decided to solve it slightly different way, because of  running in a remote server in docker.
